Repository zcash/zips, pull requests merged in 2024-02, with the labels that each got.

#778 ZIPs 226, 227, and 230 - ZSA Protocol: Transfer, Issuance and Burn
  README.rst
  README.template
  css/style.css
  index.html
  zip-0226.html
  zip-0226.rst
  zip-0227-asset-identifier-relation.png
  zip-0227-asset-identifier-relation.svg
  zip-0227-key-components-zsa.png
  zip-0227-key-components-zsa.svg
  zip-0227.html
  zip-0227.rst
  zip-0230.html
  zip-0230.rst
Labels: ZSAs

#765 ZIP 316 Revision 1, and corresponding updates to ZIP 320
  zip-0316.html
  zip-0316.rst
  zip-0320.html
  zip-0320.rst
Labels: ZIP idea, ZIP clarification

#784 ZIP 316: fix a typo and remove trailing spaces
  zip-0316.html
  zip-0316.rst
Labels: C-cleanup
